[package]
name = "lok"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
wayland-client = "0.31"
# 增加 unstable 特性
wayland-protocols = { version = "0.31", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
libc = "0.2"
cosmic-text = "0.11"
pinyin = "0.10"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = "z"
