[package]
name = "lok"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
libc = "0.2"
cosmic-text = "0.11"
# 移除 xkbcommon

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
