[package]
name = "lokmenu"
version = "0.1.0"
edition = "2021"
description = "A CJK-optimized Wayland menu tool"
license = "MIT"
repository = "https://github.com/fajknli/lok"
keywords = ["wayland", "menu", "dmenu", "pinyin", "cjk"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
wayland-client = "0.31"
# 确保启用了 client, staging, unstable 特性
wayland-protocols = { version = "0.31", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
libc = "0.2"
cosmic-text = "0.11"
pinyin = "0.10"
rayon = "1.10"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = "z"
